### ISSUE TITLE
Json Object instead of Class

### ISSUE THREAD

**Issue by TeodorKolev** [albertovecina/PaperKnife#1]
Is it possible to use json object instead of Class `Item`?

**Comment by albertovecina** [comment]
Could you be more specific?

**Comment by albertovecina** [comment]
You can implements the CellElement interface in the object you prefer. You could use an item that extends of JSONObject and implements CellElement. It responds to your question?

**Comment by TeodorKolev** [comment]
The main issue is that I must define Class to implement interface. I cannot implement interface on json object as far as I know. So, if I have a nested json value that has to be taken, I have to define other classes for nested jsons. I prefer to use json instead converting json to tons of Classes with their own props getters setters etc.

**Comment by TeodorKolev** [comment]
Another question. Since Adapter is in presenter, is it proper to define Adapter view in presenter?

**Comment by albertovecina** [comment]
This library is designed to isolate the data model (preferably mapped domain objects) from the Android framework dependencies. I work with the data in this way: JSON Object -> Model Object -> Domain Object (adapted to your view needs and extends CellElement). Basically this library is created to avoid Android Framework dependencies in the presentation layer (0 android imports in the presenter). In my opinion this “rule” is very useful to get a impartial criteria to organize the layers.

**Comment by TeodorKolev** [comment]
So, if I have to display `jsonObject.getJsonObject(someVal).getJsonObject(someVal2).getString("string")` I have to create ClassOne, ClassTwo, ClassThree> prop string. ClassOne>ListAllClassesTwo>ListAllClassesThree>get prop

**Comment by TeodorKolev** [comment]
My othere question: since Adapter is in presenter is it proper to set 
`convertView = LayoutInflater.from(parent.getContext()).inflate(R.layout.myView, parent, false);`
inside

**Comment by albertovecina** [comment]
Here you have an Adapter implementation using PaperKnife:

https://github.com/albertovecina/PaperKnife/blob/master/paperknife-sample/src/main/java/com/vsa/paperknifesample/adapter/CustomAdapter.java

Anyway you can contact me in my personal mail (I gave it in twitter) and I'll try to share my opinions about other topics.
